\input texinfo.tex
@c %**start of header
@setfilename mmux-bash-pointers.info
@settitle MMUX Bash Pointers
@c %**end of header

@include version.texi
@include macros.texi

@c page
@c ------------------------------------------------------------
@c Values.
@c ------------------------------------------------------------

@set TITLE                      MMUX Bash Pointers

@c To be used as @value{PACKAGE} whenever we need to include the full
@c name of this package.
@set PACKAGE                    MMUX Bash Pointers

@c To be used as @value{PACKAGE} whenever we need to include the
@c nickname of the project: the name that is used to compose the
@c distribution tarball or the web address.
@set PACKAGE_NICKNAME           mmux-bash-pointers

@c To be used as @value{AUTHOR} whenever we need to include the list of
@c authors of this document.
@set AUTHOR                     Marco Maggi

@c To be used as @value{AUTHOR_EMAIL} whenever we need to include the
@c email of the *single* author of this document.
@set AUTHOR_EMAIL               @email{mrc.mgg@@gmail.com}

@c To be used as @value{COPYRIGHT_YEARS} whenever we need to include the
@c list of copyright years.
@set COPYRIGHT_YEARS            2024

@c ------------------------------------------------------------

@set PackageAutoconfPrefix              MMUX_BASH_POINTERS
@set PackagePkgconfigModule             mmux-bash-pointers
@set PackageLibsVar                     @env{MMUX_BASH_POINTERS_LIBS}
@set PackageCflagsVar                   @env{MMUX_BASH_POINTERS_CFLAGS}
@c This is the stem of the library in "libmmux-bash-pointers.so".
@set PackageLibstem                     mmux-bash-pointers
@set PackageApiPrefixLower              mmux_bash_pointers_
@set PackageApiPrefixUpper              MMUX_BASH_POINTERS_

@set PackageHeader                      mmux-bash-pointers.h
@set PackageHeaderFile                  @file{@value{PackageHeader}}

@set GithubUrl                 @url{https://github.com/marcomaggi/@value{PACKAGE_NICKNAME}}
@set BitbucketUrl              @url{https://bitbucket.org/marcomaggi/@value{PACKAGE_NICKNAME}}
@set DownloadUrl               @url{https://bitbucket.org/marcomaggi/@value{PACKAGE_NICKNAME}/downloads}
@set DocumentationUrl          @url{https://marcomaggi.github.io/docs/@value{PACKAGE_NICKNAME}.html}

@c page
@c ------------------------------------------------------------
@c Local macros.
@c ------------------------------------------------------------



@c page
@c ------------------------------------------------------------
@c Copyright notice.
@c ------------------------------------------------------------

@copying

This document describes version @value{VERSION} of @value{PACKAGE}, a package implementing
additional builtin commands for the @gnu{} Bash shell; to do so it installs a C language library and
a shell script which is meant to be sourced in a Bash session or script.

The package targets @posix{} platforms.  Only for testing: this package depends on the external
package @acronym{MBFL} (at least version @samp{v3.0.0-devel.8}).

This package is distributed under the terms of the @gnu{} Lesser General Public License (@lgpl{}).

The latest release can be downloaded from:

@center @value{DownloadUrl}

@noindent
development takes place at:

@center @value{GithubUrl}

@noindent
and as backup at:

@center @value{BitbucketUrl}

@noindent
Copyright @copyright{} @value{COPYRIGHT_YEARS} by @value{AUTHOR} @value{AUTHOR_EMAIL}

@quotation
Permission is granted to copy, distribute and/or modify this document under the terms of the @gnu{}
Free Documentation License, Version 1.3 or any later version published by the Free Software
Foundation; with Invariant Sections being ``@gnu{} Free Documentation License'' and ``@gnu{} Lesser
General Public License'', no Front--Cover Texts, and no Back--Cover Texts.  A copy of the license is
included in the section entitled ``@gnu{} Free Documentation License''.
@end quotation
@end copying

@c page
@c ------------------------------------------------------------
@c Headers.
@c ------------------------------------------------------------

@titlepage
@title @value{TITLE}
@subtitle Revision @value{VERSION}
@author @value{AUTHOR} @value{AUTHOR_EMAIL}
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c ------------------------------------------------------------

@ifinfo
@dircategory Development
@direntry
* mmux-bash-pointers: (mmux-bash-pointers).  Additional GNU Bash builtins.
@end direntry
@end ifinfo

@c ------------------------------------------------------------

@ignore
@syncodeindex tp cp
@syncodeindex vr cp
@syncodeindex fn cp
@end ignore

@c page
@ifnottex
@node Top
@top @value{TITLE}

@insertcopying

@menu
* overview::                    Overview of the package.
* version::                     Version functions.
* variables::                   Global variables.
* memory::                      Standard memory allocation.
* pointers::                    Memory block accessors and mutators.

Appendices

* Package License::             GNU Lesser General Public License.
* Documentation License::       GNU Free Documentation License.
* references::                  Bibliography and references.

Indexes

* concept index::               An entry for each concept.
* function index::              An entry for each function.
* variable index::              An entry for each variable.
* type index::                  An entry for each type.
@end menu
@end ifnottex

@c page
@node overview
@chapter Overview of the package


This document describes version @value{VERSION} of @value{PACKAGE}, a package implementing
additional builtin commands for the @gnu{} Bash shell; to do so it installs a C language library and
a shell script which is meant to be sourced in a Bash session or script.

@value{PACKAGE} installs a shared library under @code{$libdir}; for example:

@center @file{/usr/local/lib64/libmmux-bash-pointers.so}

@noindent
it also installs a shell script, a ``shell library'', under @code{$datavar/bash}; for example:

@center @file{/usr/local/share/bash/libmmux-bash-pointers.bash}

@noindent
to use the builtins, we have to load the shell library using the builtin @code{source}.

@menu
* overview linking::            Linking code with the library.
@end menu

@include overview-linking.texi

@c page
@node version
@chapter Version functions


The installed libraries follow version numbering as established by the @gnu{} Autotools.  For an
explanation of interface numbers as managed by @gnu{} Libtool @xref{Libtool versioning, interface,
Libtool's versioning system, libtool, Shared library support for @gnu{}}.


@deftypefun {char const *} mmux_bash_pointers_version_string (void)
Return a pointer to a statically allocated @asciiz{} string representing the interface version
number.
@end deftypefun


@deftypefun int mmux_bash_pointers_version_interface_current (void)
Return an integer representing the library interface current number.
@end deftypefun


@deftypefun int mmux_bash_pointers_version_interface_revision (void)
Return an integer representing the library interface current revision number.
@end deftypefun


@deftypefun int mmux_bash_pointers_version_interface_age (void)
Return an integer representing the library interface current age.
@end deftypefun

@c page
@node variables
@chapter Global variables


@macro MmuxDefineGlobalVar{VARNAME}
@defvar \VARNAME\
Global variable holding the size of the specified C language type.
@end defvar

@end macro

@MmuxDefineGlobalVar{SIZEOF_SCHAR}
@MmuxDefineGlobalVar{SIZEOF_UCHAR}
@MmuxDefineGlobalVar{SIZEOF_SINT}
@MmuxDefineGlobalVar{SIZEOF_UINT}
@MmuxDefineGlobalVar{SIZEOF_SLONG}
@MmuxDefineGlobalVar{SIZEOF_ULONG}
@MmuxDefineGlobalVar{SIZEOF_FLOAT}
@MmuxDefineGlobalVar{SIZEOF_DOUBLE}
@MmuxDefineGlobalVar{SIZEOF_LDOUBLE}

@c page
@node memory
@chapter Standard memory allocation


Basically, to allocate new memory we should do:

@example
declare PTR

malloc PTR 123
realloc PTR $PTR 456
free $PTR
@end example

@noindent
we must remember that if we execute Bash code in a subshell: the pointers will not be valid across
shells; so the following will not work:

@example
declare PTR

$(malloc PTR 123)
free $PTR
@end example

@noindent
because @func{malloc} allocates memory in a subshell.


@deffn Builtin malloc @var{PTRVAR} @var{SIZE}
Allocate a memory block using the standard @cfunc{malloc} function; if successful return true,
otherwise return false.

The argument @var{PTRVAR} must be the name of a variable in which @func{malloc} will store a string
representation of the pointer to the newly allocated block.

The argument @var{SIZE} must be the string representation of an exact, positive integer representing
the requested number of bytes in the newly allocated block; it must fit the C language type
@objtype{size_t}.
@end deffn


@deffn Builtin realloc @var{PTRVAR} @var{OLDPTR} @var{NEWSIZE}
Reallocate a memory block using the standard @cfunc{realloc} function; if successful return true,
otherwise return false.

The argument @var{PTRVAR} must be the name of a variable in which @func{malloc} will store a string
representation of the pointer to the newly allocated block.

The argument @var{OLDPTR} must be the string representation of the old memory pointer.

The argument @var{SIZE} must be the string representation of an exact, positive integer representing
the newly requested number of bytes in the newly allocated block; it must fit the C language type
@objtype{size_t}.
@end deffn


@deffn Builtin free @var{PTR}
Release a previously allocated memory block using the standard @cfunc{free} function.
@end deffn

@c page
@node pointers
@chapter Memory block accessors and mutators


If we allocate memory using the standard C library functions, we can poke and peek values in the
memory blocks:

@example
declare PTR VALUE

malloc PTR 1024
pointer-set-double $PTR 0 1.23
pointer-ref-double VALUE $PTR 0
free $PTR
@end example

For all the following builtins, the argument:

@table @var
@item POINTER
must be the string representation of a memory pointer referencing a previously allocated block;

@item OFFSET
must be the string representation of an exact, positive integer, compatible with the C language type
@code{size_t}, representing an offset from @var{POINTER};

@item VALUE
must be the string representation of a number, compatible with a C language type: it is stored by
the mutators at @var{OFFSET} from @var{POINTER};

@item VALUEVAR
must be a string representing the name of a Bash variable: it is used by the accessors to store the
value extracted at @var{OFFSET} from @var{POINTER}.
@end table


@macro MmuxDefineAccessorMutator{STEM,TYPE}
@deffn Builtin pointer-set-\STEM\ @var{POINTER} @var{OFFSET} @var{VALUE}
@deffnx Builtin pointer-ref-\STEM\ @var{VALUEVAR} @var{POINTER} @var{OFFSET}
Accessor and mutator for memory blocks operating on C language types @code{\TYPE\}.
@end deffn

@end macro

@MmuxDefineAccessorMutator{schar,signed char}
@MmuxDefineAccessorMutator{uchar,unsigned char}
@MmuxDefineAccessorMutator{sint,signed int}
@MmuxDefineAccessorMutator{uint,unsigned int}
@MmuxDefineAccessorMutator{slong,signed long}
@MmuxDefineAccessorMutator{ulong,unsigned long}
@MmuxDefineAccessorMutator{ssize,ssize_t}
@MmuxDefineAccessorMutator{usize,size_t}
@MmuxDefineAccessorMutator{float,float}
@MmuxDefineAccessorMutator{double,double}
@MmuxDefineAccessorMutator{ldouble,long double}
@MmuxDefineAccessorMutator{complex,double complex}

@c page
@c ------------------------------------------------------------
@c Appendices.
@c ------------------------------------------------------------

@include lgpl-3.0.texi
@include fdl-1.3.texi

@c page
@node references
@appendix Bibliography and references


The documentation of @value{PACKAGE} is available online:

@center @value{DocumentationUrl}

@noindent
the latest release of this package can be downloaded from:

@center @value{DownloadUrl}

@noindent
development takes place at:

@center @value{GithubUrl}

@noindent
and as backup at:

@center @value{BitbucketUrl}

@noindent
the package @acronym{MBFL} is available online:

@center @url{http://github.com/marcomaggi/mbfl/}

@c page
@node concept index
@appendix An entry for each concept

@printindex cp

@node function index
@appendix An entry for each function.

@printindex fn

@node variable index
@appendix An entry for each variable.

@printindex vr

@node type index
@appendix An entry for each type.

@printindex tp

@contents
@bye

@c end of file

