\input texinfo.tex
@c %**start of header
@setfilename mmux-bash-pointers.info
@settitle MMUX Bash Pointers
@c %**end of header

@include version.texi
@include macros.texi

@c page
@c ------------------------------------------------------------
@c Values.
@c ------------------------------------------------------------

@set TITLE                      MMUX Bash Pointers

@c To be used as @value{PACKAGE} whenever we need to include the full
@c name of this package.
@set PACKAGE                    MMUX Bash Pointers

@c To be used as @value{PACKAGE} whenever we need to include the
@c nickname of the project: the name that is used to compose the
@c distribution tarball or the web address.
@set PACKAGE_NICKNAME           mmux-bash-pointers

@c To be used as @value{AUTHOR} whenever we need to include the list of
@c authors of this document.
@set AUTHOR                     Marco Maggi

@c To be used as @value{AUTHOR_EMAIL} whenever we need to include the
@c email of the *single* author of this document.
@set AUTHOR_EMAIL               @email{mrc.mgg@@gmail.com}

@c To be used as @value{COPYRIGHT_YEARS} whenever we need to include the
@c list of copyright years.
@set COPYRIGHT_YEARS            2024

@c ------------------------------------------------------------

@set PackageAutoconfPrefix              MMUX_BASH_POINTERS
@set PackagePkgconfigModule             mmux-bash-pointers
@set PackageLibsVar                     @env{MMUX_BASH_POINTERS_LIBS}
@set PackageCflagsVar                   @env{MMUX_BASH_POINTERS_CFLAGS}
@c This is the stem of the library in "libmmux-bash-pointers.so".
@set PackageLibstem                     mmux-bash-pointers
@set PackageApiPrefixLower              mmux_bash_pointers_
@set PackageApiPrefixUpper              MMUX_BASH_POINTERS_

@set PackageHeader                      mmux-bash-pointers.h
@set PackageHeaderFile                  @file{@value{PackageHeader}}

@set GithubUrl                 @url{https://github.com/marcomaggi/@value{PACKAGE_NICKNAME}}
@set DocumentationUrl          @url{https://marcomaggi.github.io/docs/@value{PACKAGE_NICKNAME}.html}

@c page
@c ------------------------------------------------------------
@c Local macros.
@c ------------------------------------------------------------

@ifinfo
@macro mbfl{}
@acronym{MBFL}
@end macro
@end ifinfo
@ifnotinfo
@macro mbfl{}
@acronym{mbfl}
@end macro
@end ifnotinfo

@c page
@c ------------------------------------------------------------
@c Copyright notice.
@c ------------------------------------------------------------

@copying

This  document  describes  version  @value{VERSION}   of  @value{PACKAGE},  a  package  implementing
additional builtin commands for the @gnu{} Bash shell; to do so it installs a C language library and
a shell script  which is meant to  be sourced in a Bash  session or script.

This package makes raw memory pointers available in shell scripts:

@example
declare PTR VALUE

libc_malloc PTR 1024
@{
  pointer-set-sint $PTR 0 123
  pointer-ref-sint VALUE $PTR 0
@}
libc_free $PTR
$VALUE  @result{} 123
@end example

The package targets @posix{} platforms.  Only for testing: this package depends on the external
package @acronym{MBFL} (at least version @samp{v3.0.0-devel.9}).

This package is distributed under the terms of the @gnu{} Lesser General Public License (@lgpl{}).

Development of this package takes place at:

@center @value{GithubUrl}

@noindent
Copyright @copyright{} @value{COPYRIGHT_YEARS} by @value{AUTHOR} @value{AUTHOR_EMAIL}

@quotation
Permission is granted to copy, distribute and/or modify this document under the terms of the @gnu{}
Free Documentation License, Version 1.3 or any later version published by the Free Software
Foundation; with Invariant Sections being ``@gnu{} Free Documentation License'' and ``@gnu{} Lesser
General Public License'', no Front--Cover Texts, and no Back--Cover Texts.  A copy of the license is
included in the section entitled ``@gnu{} Free Documentation License''.
@end quotation
@end copying

@c page
@c ------------------------------------------------------------
@c Headers.
@c ------------------------------------------------------------

@titlepage
@title @value{TITLE}
@subtitle Revision @value{VERSION}
@author @value{AUTHOR} @value{AUTHOR_EMAIL}
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c ------------------------------------------------------------

@ifinfo
@dircategory Development
@direntry
* mmux-bash-pointers: (mmux-bash-pointers).  Additional GNU Bash builtins.
@end direntry
@end ifinfo

@c ------------------------------------------------------------

@ignore
@syncodeindex tp cp
@syncodeindex vr cp
@syncodeindex fn cp
@end ignore

@c page
@ifnottex
@node Top
@top @value{TITLE}

@insertcopying

@menu
* overview::                    Overview of the package.
* variables::                   Global variables.
* memory::                      Standard memory allocation.
* operations::                  Standard memory operations.
* pointers::                    Memory block accessors and mutators.
* arrays::                      Memory arrays accessors and mutators.
* conversions::                 Converting data to and from memory blocks.
* errors::                      Handling errors.

Appendices

* Package License::             GNU Lesser General Public License.
* Documentation License::       GNU Free Documentation License.
* shared library::              Using the shared library.
* references::                  Bibliography and references.

Indexes

* concept index::               An entry for each concept.
* function index::              An entry for each function.
* variable index::              An entry for each variable.
* type index::                  An entry for each type.
@end menu
@end ifnottex

@c page
@node overview
@chapter Overview of the package


This document describes version @value{VERSION} of @value{PACKAGE}, a package implementing
additional builtin commands for the @gnu{} Bash shell; to do so it installs a C language library and
a shell script which is meant to be sourced in a Bash session or script.

This package makes raw memory pointers available in shell scripts:

@example
declare PTR VALUE

libc_malloc PTR 1024
@{
  pointer-set-sint $PTR 0 123
  pointer-ref-sint VALUE $PTR 0
@}
libc_free $PTR
$VALUE  @result{} 123
@end example

@menu
* overview install::            Installed files.
* overview linking::            Linking code with the library.
@end menu

@c page
@node overview install
@section Installed files


@value{PACKAGE} installs a shell script, a ``shell library'', under @code{$datavar/bash}; for
example:

@center @file{/usr/local/share/bash/libmmux-bash-pointers.bash}

@noindent
to use the builtins, we have to load the shell library using Bash's builtin @code{source}.  A shared
library, actually implementing the builtins, is installed under @code{$libdir}; for example:

@center @file{/usr/local/lib64/libmmux-bash-pointers.so}

@noindent
the shared library is automatically loaded by the shell library.

A C language header file is also installed under @code{$includedire}, for example:

@center @file{/usr/local/include/libmmux-bash-pointers.h}

@noindent
we can write code that links to the shared library to reuse some of its facilities.

@c page

@include overview-linking.texi

@c page
@node variables
@chapter Global variables


The shell library installed by @value{PACKAGE} defines global variables to allow inspection of the
underlying C language platform.

@menu
* variables version::           Version variables.
* variables sizeof::            C language type sizes.
* variables errno::             Value of @code{errno}.
@end menu

@c page
@node variables version
@section Version variables


The installed libraries follow version numbering as established by the @gnu{} Autotools.  For an
explanation of interface numbers as managed by @gnu{} Libtool @xref{Libtool versioning, interface,
Libtool's versioning system, libtool, Shared library support for @gnu{}}.


@defvr {Shell Variable} MMUX_BASH_POINTERS_CURRENT
An integer representing the library interface current number.
@end defvr


@defvr {Shell Variable} MMUX_BASH_POINTERS_REVISION
An integer representing the library interface current revision number.
@end defvr


@defvr {Shell Variable} MMUX_BASH_POINTERS_AGE
An integer representing the library interface current age.
@end defvr

@c page
@node variables sizeof
@section C language type sizes


If a C language type referenced by one of the following variables is undefined: the corresponding
Bash variable is undefined; we can test this condition with @code{test -v}; to test if the
underlying platform implements the type @code{long long}, we can do:

@example
if test -v libc_SIZEOF_SLLONG
then # implemented
else # not implemented
fi
@end example

@macro MmuxDefineGlobalVarSizeof{NAME,TYPE}
@defvar libc_SIZEOF_\NAME\
Global variable holding the size, measured in bytes, of the C language type @code{\TYPE\}.
@end defvar

@end macro

@MmuxDefineGlobalVarSizeof{POINTER,void *}

@MmuxDefineGlobalVarSizeof{SCHAR, signed char}
@MmuxDefineGlobalVarSizeof{UCHAR, unsigned char}
@MmuxDefineGlobalVarSizeof{SINT, signed int}
@MmuxDefineGlobalVarSizeof{UINT, unsigned int}
@MmuxDefineGlobalVarSizeof{SLONG, signed long int}
@MmuxDefineGlobalVarSizeof{ULONG, unsigned long int}
@MmuxDefineGlobalVarSizeof{SLLONG, signed long long int}
@MmuxDefineGlobalVarSizeof{ULLONG, unsigned long long int}
@MmuxDefineGlobalVarSizeof{FLOAT, float}
@MmuxDefineGlobalVarSizeof{DOUBLE, double}
@MmuxDefineGlobalVarSizeof{LDOUBLE, long double}
@MmuxDefineGlobalVarSizeof{COMPLEX, double complex}

@MmuxDefineGlobalVarSizeof{SINT8, int8_t}
@MmuxDefineGlobalVarSizeof{UINT8, uint8_t}
@MmuxDefineGlobalVarSizeof{SINT16, int16_t}
@MmuxDefineGlobalVarSizeof{UINT16, uint16_t}
@MmuxDefineGlobalVarSizeof{SINT32, int32_t}
@MmuxDefineGlobalVarSizeof{UINT32, uint32_t}
@MmuxDefineGlobalVarSizeof{SINT64, int64_t}
@MmuxDefineGlobalVarSizeof{UINT64, uint64_t}

@MmuxDefineGlobalVarSizeof{SSIZE, ssize_t}
@MmuxDefineGlobalVarSizeof{USIZE, size_t}
@MmuxDefineGlobalVarSizeof{INTMAX, intmax_t}
@MmuxDefineGlobalVarSizeof{INTPTR, intptr_t}
@MmuxDefineGlobalVarSizeof{MODE, mode_t}
@MmuxDefineGlobalVarSizeof{OFF, off_t}
@MmuxDefineGlobalVarSizeof{PID, pid_t}
@MmuxDefineGlobalVarSizeof{UID, uid_t}
@MmuxDefineGlobalVarSizeof{GID, gid_t}

@c page
@node variables errno
@section Value of @code{errno}


If a C language constant referenced by one of the following variables is undefined: the
corresponding Bash variable is undefined; we can test this condition with @code{test -v}; to test if
the underlying platform implements the constant @code{ENOMEM}, we can do:

@example
if test -v libc_ENOMEM
then # implemented
else # not implemented
fi
@end example

@macro MmuxDefineGlobalVarErrno{NAME}
@defvar libc_\NAME\
Global variable holding the value of the C language constant @code{\NAME\}.
@end defvar

@end macro

@MmuxDefineGlobalVarErrno{EPERM}
@MmuxDefineGlobalVarErrno{ENOENT}
@MmuxDefineGlobalVarErrno{ESRCH}
@MmuxDefineGlobalVarErrno{EINTR}
@MmuxDefineGlobalVarErrno{EIO}
@MmuxDefineGlobalVarErrno{ENXIO}
@MmuxDefineGlobalVarErrno{E2BIG}
@MmuxDefineGlobalVarErrno{ENOEXEC}
@MmuxDefineGlobalVarErrno{EBADF}
@MmuxDefineGlobalVarErrno{ECHILD}
@MmuxDefineGlobalVarErrno{EAGAIN}
@MmuxDefineGlobalVarErrno{ENOMEM}
@MmuxDefineGlobalVarErrno{EACCES}
@MmuxDefineGlobalVarErrno{EFAULT}
@MmuxDefineGlobalVarErrno{ENOTBLK}
@MmuxDefineGlobalVarErrno{EBUSY}
@MmuxDefineGlobalVarErrno{EEXIST}
@MmuxDefineGlobalVarErrno{EXDEV}
@MmuxDefineGlobalVarErrno{ENODEV}
@MmuxDefineGlobalVarErrno{ENOTDIR}
@MmuxDefineGlobalVarErrno{EISDIR}
@MmuxDefineGlobalVarErrno{EINVAL}
@MmuxDefineGlobalVarErrno{ENFILE}
@MmuxDefineGlobalVarErrno{EMFILE}
@MmuxDefineGlobalVarErrno{ENOTTY}
@MmuxDefineGlobalVarErrno{ETXTBSY}
@MmuxDefineGlobalVarErrno{EFBIG}
@MmuxDefineGlobalVarErrno{ENOSPC}
@MmuxDefineGlobalVarErrno{ESPIPE}
@MmuxDefineGlobalVarErrno{EROFS}
@MmuxDefineGlobalVarErrno{EMLINK}
@MmuxDefineGlobalVarErrno{EPIPE}
@MmuxDefineGlobalVarErrno{EDOM}
@MmuxDefineGlobalVarErrno{ERANGE}
@MmuxDefineGlobalVarErrno{EDEADLK}
@MmuxDefineGlobalVarErrno{ENAMETOOLONG}
@MmuxDefineGlobalVarErrno{ENOLCK}
@MmuxDefineGlobalVarErrno{ENOSYS}
@MmuxDefineGlobalVarErrno{ENOTEMPTY}
@MmuxDefineGlobalVarErrno{ELOOP}
@MmuxDefineGlobalVarErrno{EWOULDBLOCK}
@MmuxDefineGlobalVarErrno{ENOMSG}
@MmuxDefineGlobalVarErrno{EIDRM}
@MmuxDefineGlobalVarErrno{ECHRNG}
@MmuxDefineGlobalVarErrno{EL2NSYNC}
@MmuxDefineGlobalVarErrno{EL3HLT}
@MmuxDefineGlobalVarErrno{EL3RST}
@MmuxDefineGlobalVarErrno{ELNRNG}
@MmuxDefineGlobalVarErrno{EUNATCH}
@MmuxDefineGlobalVarErrno{ENOCSI}
@MmuxDefineGlobalVarErrno{EL2HLT}
@MmuxDefineGlobalVarErrno{EBADE}
@MmuxDefineGlobalVarErrno{EBADR}
@MmuxDefineGlobalVarErrno{EXFULL}
@MmuxDefineGlobalVarErrno{ENOANO}
@MmuxDefineGlobalVarErrno{EBADRQC}
@MmuxDefineGlobalVarErrno{EBADSLT}
@MmuxDefineGlobalVarErrno{EDEADLOCK}
@MmuxDefineGlobalVarErrno{EBFONT}
@MmuxDefineGlobalVarErrno{ENOSTR}
@MmuxDefineGlobalVarErrno{ENODATA}
@MmuxDefineGlobalVarErrno{ETIME}
@MmuxDefineGlobalVarErrno{ENOSR}
@MmuxDefineGlobalVarErrno{ENONET}
@MmuxDefineGlobalVarErrno{ENOPKG}
@MmuxDefineGlobalVarErrno{EREMOTE}
@MmuxDefineGlobalVarErrno{ENOLINK}
@MmuxDefineGlobalVarErrno{EADV}
@MmuxDefineGlobalVarErrno{ESRMNT}
@MmuxDefineGlobalVarErrno{ECOMM}
@MmuxDefineGlobalVarErrno{EPROTO}
@MmuxDefineGlobalVarErrno{EMULTIHOP}
@MmuxDefineGlobalVarErrno{EDOTDOT}
@MmuxDefineGlobalVarErrno{EBADMSG}
@MmuxDefineGlobalVarErrno{EOVERFLOW}
@MmuxDefineGlobalVarErrno{ENOTUNIQ}
@MmuxDefineGlobalVarErrno{EBADFD}
@MmuxDefineGlobalVarErrno{EREMCHG}
@MmuxDefineGlobalVarErrno{ELIBACC}
@MmuxDefineGlobalVarErrno{ELIBBAD}
@MmuxDefineGlobalVarErrno{ELIBSCN}
@MmuxDefineGlobalVarErrno{ELIBMAX}
@MmuxDefineGlobalVarErrno{ELIBEXEC}
@MmuxDefineGlobalVarErrno{EILSEQ}
@MmuxDefineGlobalVarErrno{ERESTART}
@MmuxDefineGlobalVarErrno{ESTRPIPE}
@MmuxDefineGlobalVarErrno{EUSERS}
@MmuxDefineGlobalVarErrno{ENOTSOCK}
@MmuxDefineGlobalVarErrno{EDESTADDRREQ}
@MmuxDefineGlobalVarErrno{EMSGSIZE}
@MmuxDefineGlobalVarErrno{EPROTOTYPE}
@MmuxDefineGlobalVarErrno{ENOPROTOOPT}
@MmuxDefineGlobalVarErrno{EPROTONOSUPPORT}
@MmuxDefineGlobalVarErrno{ESOCKTNOSUPPORT}
@MmuxDefineGlobalVarErrno{EOPNOTSUPP}
@MmuxDefineGlobalVarErrno{EPFNOSUPPORT}
@MmuxDefineGlobalVarErrno{EAFNOSUPPORT}
@MmuxDefineGlobalVarErrno{EADDRINUSE}
@MmuxDefineGlobalVarErrno{EADDRNOTAVAIL}
@MmuxDefineGlobalVarErrno{ENETDOWN}
@MmuxDefineGlobalVarErrno{ENETUNREACH}
@MmuxDefineGlobalVarErrno{ENETRESET}
@MmuxDefineGlobalVarErrno{ECONNABORTED}
@MmuxDefineGlobalVarErrno{ECONNRESET}
@MmuxDefineGlobalVarErrno{ENOBUFS}
@MmuxDefineGlobalVarErrno{EISCONN}
@MmuxDefineGlobalVarErrno{ENOTCONN}
@MmuxDefineGlobalVarErrno{ESHUTDOWN}
@MmuxDefineGlobalVarErrno{ETOOMANYREFS}
@MmuxDefineGlobalVarErrno{ETIMEDOUT}
@MmuxDefineGlobalVarErrno{ECONNREFUSED}
@MmuxDefineGlobalVarErrno{EHOSTDOWN}
@MmuxDefineGlobalVarErrno{EHOSTUNREACH}
@MmuxDefineGlobalVarErrno{EALREADY}
@MmuxDefineGlobalVarErrno{EINPROGRESS}
@MmuxDefineGlobalVarErrno{ESTALE}
@MmuxDefineGlobalVarErrno{EUCLEAN}
@MmuxDefineGlobalVarErrno{ENOTNAM}
@MmuxDefineGlobalVarErrno{ENAVAIL}
@MmuxDefineGlobalVarErrno{EISNAM}
@MmuxDefineGlobalVarErrno{EREMOTEIO}
@MmuxDefineGlobalVarErrno{EDQUOT}
@MmuxDefineGlobalVarErrno{ENOMEDIUM}
@MmuxDefineGlobalVarErrno{EMEDIUMTYPE}
@MmuxDefineGlobalVarErrno{ECANCELED}
@MmuxDefineGlobalVarErrno{ENOKEY}
@MmuxDefineGlobalVarErrno{EKEYEXPIRED}
@MmuxDefineGlobalVarErrno{EKEYREVOKED}
@MmuxDefineGlobalVarErrno{EKEYREJECTED}
@MmuxDefineGlobalVarErrno{EOWNERDEAD}
@MmuxDefineGlobalVarErrno{ENOTRECOVERABLE}

@c page
@node memory
@chapter Standard memory allocation


Basically, to allocate new memory we should do:

@example
declare PTR

if libc_malloc PTR 123
then exit 1
fi
@{
  # do something
@}
libc_free $PTR
@end example

@noindent
we must remember that if we execute code in a subshell: the pointers will not be valid across
shells; so the following will not work:

@example
declare PTR

$(libc_malloc PTR 123)
libc_free $PTR
@end example

@noindent
because @func{libc_malloc} allocates memory in a subshell.


@deffn Builtin libc_malloc @var{PTRVAR} @var{SIZE}
Allocate a memory block using the standard @cfunc{malloc} function; if successful return true,
otherwise return false.

The argument @var{PTRVAR} must be the name of a variable in which this builtin will store a string
representation of the pointer to the newly allocated block.

The argument @var{SIZE} must be the string representation of an exact, positive integer representing
the requested number of bytes in the newly allocated block; it must fit the C language type
@objtype{size_t}.
@end deffn


@deffn Builtin libc_calloc @var{PTRVAR} @var{ITEM_COUNT} @var{ITEM_SIZE}
Allocate a memory block using the standard @cfunc{calloc} function; if successful return true,
otherwise return false.

The argument @var{PTRVAR} must be the name of a variable in which this builtin will store a string
representation of the pointer to the newly allocated block.

The argument @var{ITEM_COUNT} must be the string representation of an exact, positive integer
representing the number of items the memory block has to contain; it must fit the C language type
@objtype{size_t}.

The argument @var{ITEM_SIZE} must be the string representation of an exact, positive integer
representing the size of each item the memory block has to contain; it must fit the C language type
@objtype{size_t}.
@end deffn


@deffn Builtin libc_realloc @var{PTRVAR} @var{OLDPTR} @var{NEWSIZE}
Reallocate a memory block using the standard @cfunc{realloc} function; if successful return true,
otherwise return false.

The argument @var{PTRVAR} must be the name of a variable in which this builtin will store a string
representation of the pointer to the newly allocated block.

The argument @var{OLDPTR} must be the string representation of the old memory pointer.

The argument @var{SIZE} must be the string representation of an exact, positive integer representing
the newly requested number of bytes in the newly allocated block; it must fit the C language type
@objtype{size_t}.
@end deffn


@deffn Builtin libc_free @var{PTR}
Release a previously allocated memory block using the standard @cfunc{free} function.

The argument @var{PTR} must be the string representation of a memory pointer referencing a
previously allocated block.
@end deffn

@c page
@node operations
@chapter Standard memory operations


@deffn Builtin libc_memset @var{PTR} @var{BYTE} @var{SIZE}
Interface to the standard C language function @cfunc{memset}.

The argument @var{PTR} must be the string representation of a pointer referencing a previously
allocated memory block.

The argument @var{BYTE} must be the string representation of an exact, positive integer representing
the value to which memory bytes must be set; it must fit an unsigned 8-bit integer.

The argument @var{SIZE} must be the string representation of an exact, positive integer representing
the number of bytes to set to @var{BYTE}; it must fit the C language type @objtype{size_t}.

@example
declare PTR SIZE=123

libc_malloc PTR $SIZE
libc_memset $PTR 1 $SIZE
@end example
@end deffn


@deffn Builtin libc_memcpy @var{PTR_TO} @var{PTR_FROM} @var{SIZE}
Interface to the standard C language function @cfunc{memcpy}.

The argument @var{PTR_TO} must be the string representation of a pointer referencing a previously
allocated memory block; the referenced memory is the destination of the copy operation.

The argument @var{PTR_FROM} must be the string representation of a pointer referencing a previously
allocated memory block; the referenced memory is the source of the copy operation.

The argument @var{SIZE} must be the string representation of an exact, positive integer representing
the number of bytes to copy; it must fit the C language type @objtype{size_t}.

@example
declare PTR_FROM PTR_TO SIZE=123

libc_malloc PTR_FROM $SIZE
libc_malloc PTR_TO   $SIZE

libc_memcpy $PTR_TO $PTR_FROM $SIZE
@end example
@end deffn


@deffn Builtin libc_memmove @var{PTR_TO} @var{PTR_FROM} @var{SIZE}
Interface to the standard C language function @cfunc{memmove}.

The argument @var{PTR_TO} must be the string representation of a pointer referencing a previously
allocated memory block; the referenced memory is the destination of the copy operation.

The argument @var{PTR_FROM} must be the string representation of a pointer referencing a previously
allocated memory block; the referenced memory is the source of the copy operation.

The argument @var{SIZE} must be the string representation of an exact, positive integer representing
the number of bytes to copy.

@example
declare PTR_FROM PTR_TO SIZE=123

libc_malloc PTR_FROM $SIZE
libc_malloc PTR_TO   $SIZE

libc_memmove $PTR_TO $PTR_FROM $SIZE
@end example
@end deffn

@c page
@node pointers
@chapter Memory block accessors and mutators


If we allocate memory using the standard C library functions, we can poke and peek values in the
memory blocks:

@example
declare PTR VALUE

libc_malloc PTR 1024
@{
  pointer-set-double $PTR 0 1.23
  pointer-ref-double VALUE $PTR 0
@}
libc_free $PTR
@end example

For all the following builtins, the argument:

@table @var
@item POINTER
must be the string representation of a memory pointer referencing a previously allocated block;

@item OFFSET
must be the string representation of an exact, non--negative integer, compatible with the C language
type @code{size_t}, representing an offset from @var{POINTER} @strong{measured in bytes};

@item VALUE
must be the string representation of a number, compatible with a C language type of the specific
mutator: it is stored by the mutators at @var{OFFSET} from @var{POINTER};

@item VALUEVAR
must be a string representing the name of a shell variable: it is used by the accessors to store the
value extracted at @var{OFFSET} from @var{POINTER}.
@end table

For all the following builtins: if the operation is successful, the return value is true; otherwise
the return value is false.


@macro MmuxDefineAccessorMutator{STEM,TYPE}
@deffn {Builtin Mutator} pointer-set-\STEM\ @var{POINTER} @var{OFFSET} @var{VALUE}
@deffnx {Builtin Accessor} pointer-ref-\STEM\ @var{VALUEVAR} @var{POINTER} @var{OFFSET}
Accessor and mutator for memory blocks operating on the C language type @code{\TYPE\}.
@end deffn

@end macro

@MmuxDefineAccessorMutator{pointer,void *}

@MmuxDefineAccessorMutator{schar,signed char}
@MmuxDefineAccessorMutator{uchar,unsigned char}
@MmuxDefineAccessorMutator{sint,signed int}
@MmuxDefineAccessorMutator{uint,unsigned int}
@MmuxDefineAccessorMutator{slong,signed long}
@MmuxDefineAccessorMutator{ulong,unsigned long}
@MmuxDefineAccessorMutator{sllong,signed long long}
@MmuxDefineAccessorMutator{ullong,unsigned long long}
@MmuxDefineAccessorMutator{float,float}
@MmuxDefineAccessorMutator{double,double}
@MmuxDefineAccessorMutator{ldouble,long double}
@MmuxDefineAccessorMutator{complex,double complex}

@MmuxDefineAccessorMutator{sint8,int8_t}
@MmuxDefineAccessorMutator{uint8,uint8_t}
@MmuxDefineAccessorMutator{sint16,int16_t}
@MmuxDefineAccessorMutator{uint16,uint16_t}
@MmuxDefineAccessorMutator{sint32,int32_t}
@MmuxDefineAccessorMutator{uint32,uint32_t}
@MmuxDefineAccessorMutator{sint64,int64_t}
@MmuxDefineAccessorMutator{uint64,uint64_t}

@MmuxDefineAccessorMutator{ssize,ssize_t}
@MmuxDefineAccessorMutator{usize,size_t}
@MmuxDefineAccessorMutator{intmax, intmax_t}
@MmuxDefineAccessorMutator{intptr, intptr_t}
@MmuxDefineAccessorMutator{mode, mode_t}
@MmuxDefineAccessorMutator{off, off_t}
@MmuxDefineAccessorMutator{pid, pid_t}
@MmuxDefineAccessorMutator{uid, uid_t}
@MmuxDefineAccessorMutator{gid, gid_t}

@c page
@node arrays
@chapter Memory arrays accessors and mutators


If we allocate memory using the standard C library functions, we can poke and peek values in the
memory blocks, handling them as arrays of a specified C type:

@example
declare PTR VALUE

libc_malloc PTR $(( 55 * libc_SIZEOF_ULONG ))
@{
  array-set-ulong $PTR 0 1234567890
  array-ref-ulong VALUE $PTR 0
@}
libc_free $PTR
@end example

For all the following builtins, the argument:

@table @var
@item ARRAY
must be the string representation of a memory pointer referencing a previously allocated block; the
block is to be interpreted as an array of a specified C type;

@item INDEX
must be the string representation of an exact, non--negative integer, compatible with the C language
type @code{size_t}, representing an index in @var{ARRAY};

@item VALUE
must be the string representation of a number, compatible with a C language type of the specific
mutator: it is stored by the mutators at @var{INDEX} in @var{ARRAY};

@item VALUEVAR
must be a string representing the name of a shell variable: it is used by the accessors to store the
value extracted at @var{INDEX} from @var{ARRAY}.
@end table

For all the following builtins: if the operation is successful, the return value is true; otherwise
the return value is false.


@macro MmuxDefineArrayAccessorMutator{STEM,TYPE}
@deffn {Builtin Mutator} array-set-\STEM\ @var{ARRAY} @var{INDEX} @var{VALUE}
@deffnx {Builtin Accessor} array-ref-\STEM\ @var{VALUEVAR} @var{ARRAY} @var{INDEX}
Accessor and mutator for memory blocks operating on the C language type @code{\TYPE\}.
@end deffn

@end macro

@MmuxDefineArrayAccessorMutator{pointer,void *}

@MmuxDefineArrayAccessorMutator{schar,signed char}
@MmuxDefineArrayAccessorMutator{uchar,unsigned char}
@MmuxDefineArrayAccessorMutator{sint,signed int}
@MmuxDefineArrayAccessorMutator{uint,unsigned int}
@MmuxDefineArrayAccessorMutator{slong,signed long}
@MmuxDefineArrayAccessorMutator{ulong,unsigned long}
@MmuxDefineArrayAccessorMutator{sllong,signed long long}
@MmuxDefineArrayAccessorMutator{ullong,unsigned long long}
@MmuxDefineArrayAccessorMutator{float,float}
@MmuxDefineArrayAccessorMutator{double,double}
@MmuxDefineArrayAccessorMutator{ldouble,long double}
@MmuxDefineArrayAccessorMutator{complex,double complex}

@MmuxDefineArrayAccessorMutator{sint8,int8_t}
@MmuxDefineArrayAccessorMutator{uint8,uint8_t}
@MmuxDefineArrayAccessorMutator{sint16,int16_t}
@MmuxDefineArrayAccessorMutator{uint16,uint16_t}
@MmuxDefineArrayAccessorMutator{sint32,int32_t}
@MmuxDefineArrayAccessorMutator{uint32,uint32_t}
@MmuxDefineArrayAccessorMutator{sint64,int64_t}
@MmuxDefineArrayAccessorMutator{uint64,uint64_t}

@MmuxDefineArrayAccessorMutator{ssize,ssize_t}
@MmuxDefineArrayAccessorMutator{usize,size_t}
@MmuxDefineArrayAccessorMutator{intmax, intmax_t}
@MmuxDefineArrayAccessorMutator{intptr, intptr_t}
@MmuxDefineArrayAccessorMutator{mode, mode_t}
@MmuxDefineArrayAccessorMutator{off, off_t}
@MmuxDefineArrayAccessorMutator{pid, pid_t}
@MmuxDefineArrayAccessorMutator{uid, uid_t}
@MmuxDefineArrayAccessorMutator{gid, gid_t}

@c page
@node conversions
@chapter Converting data to and from memory blocks


@menu
* conversions arrays::          Converting data to and from index arrays.
* conversions strings::         Converting data to and from strings.
@end menu

@c page
@node conversions arrays
@section Converting data to and from index arrays


@defun mmux-bash-pointers-array-from-memory @var{ARRY_TO} @var{PTR_FROM} @var{SIZE}
Copy byte by byte data from a memory block into a Bash index array.

The argument @var{ARRY_TO} must be a string representing the name of a Bash index array; this
function stores in this array the bytes from the memory block, starting from index zero.

The argument @var{PTR_FROM} must be the string representation of a pointer referencing a previously
allocated memory block; the referenced memory is the source of the copy operation.

The argument @var{SIZE} must be the string representation of an exact, positive integer representing
the number of bytes to copy; it must fit the C language type @objtype{size_t}.

@example
declare POINTER
declare -i SIZE=5
declare -a ARRY

if ! libc_malloc POINTER $SIZE
then exit 1
fi

mmux-bash-pointers-array-from-memory ARRY $POINTER $SIZE
@end example
@end defun


@defun mmux-bash-pointers-memory-from-array @var{PTR_TO} @var{ARRY_FROM} @var{SIZE}
Copy byte by byte data from a Bash index array into a memory block.

The argument @var{PTR_TO} must be the string representation of a pointer referencing a previously
allocated memory block; the referenced memory is the target of the copy operation.

The argument @var{ARRY_FROM} must be a string representing the name of a Bash index array; this
function reads from this array the bytes to store in the memory block, starting from index zero.

The argument @var{SIZE} must be the string representation of an exact, positive integer representing
the number of bytes to copy; it must fit the C language type @objtype{size_t}.

@example
declare POINTER
declare -i SIZE=5
declare -a ARRY=(1 2 3 4 5)

if ! libc_malloc POINTER $SIZE
then exit 1
fi

mmux-bash-pointers-memory-from-array $POINTER ARRY $SIZE
@end example
@end defun

@c page
@node conversions strings
@section Converting data to and from strings


@defun mmux-bash-pointers-string-from-memory @var{STRINGVAR_TO} @var{PTR_FROM} @var{SIZE}
Copy byte by byte data from a memory block into a Bash string.

The argument @var{STRINGVAR_TO} must be a string representing a Bash variable name; this function
stores in this variable a string built with the bytes from the memory block, starting from index
zero.

The argument @var{PTR_FROM} must be the string representation of a pointer referencing a previously
allocated memory block; the referenced memory is the source of the copy operation.

The argument @var{SIZE} must be the string representation of an exact, positive integer representing
the number of bytes to copy; it must fit the C language type @objtype{size_t}.

@example
declare POINTER
declare -i SIZE=5
declare STRING

if ! libc_malloc POINTER $SIZE
then exit 1
fi

mmux-bash-pointers-string-from-memory STRING $POINTER $SIZE
@end example
@end defun


@defun mmux-bash-pointers-memory-from-string @var{PTR_TO} @var{STRING_FROM} @var{SIZE}
Copy byte by byte data from a Bash string into a memory block.

The argument @var{PTR_TO} must be the string representation of a pointer referencing a previously
allocated memory block; the referenced memory is the target of the copy operation.

The argument @var{STRING_FROM} must be a string; this function reads from this strings the bytes to
store in the memory block, starting from index zero.

The argument @var{SIZE} must be the string representation of an exact, positive integer representing
the number of bytes to copy; it must fit the C language type @objtype{size_t}.

@example
declare POINTER
declare -i SIZE=5
declare -a STRING="12345"

if ! libc_malloc POINTER $SIZE
then exit 1
fi

mmux-bash-pointers-memory-from-string $POINTER $STRING $SIZE
@end example
@end defun

@c page
@node errors
@chapter Handling errors


@defvr {Shell Variable} ERRNO
If an error occurs in the call to a builtin that interfaces a Standard C Library function: the
builtin will set the shell variable @env{ERRNO} to the string representation of an exact integer,
itself representing a standard @code{errno} code.

@example
declare PTR ERRNO=0 SYM

libc_malloc PTR 'ciao'
mmux-bash-pointers-errno-to-string SYM $ERRNO
$SYM    @result{} EINVAL
@end example
@end defvr


@deffn Builtin libc_strerror @var{MSGVAR} @var{ERRNUM}
Store in @var{MSGVAR} the error message corresponding to @var{ERRNUM}, which must be the string
representation of an exact integer representing a valid value for @code{errno}; @var{ERRNUM} must
fit the C language type @code{int}.

@example
declare MSG

if test -v libc_EINVAL
then libc_strerror MSG $libc_EINVAL
else MSG='EINVAL undefined'
fi

"$MSG"  @result{} Invalid argument
@end example
@end deffn


@defun mmux-bash-pointers-errno-to-string @var{SYMVAR} @var{ERRNUM}
Store in @var{SYMVAR} a string representation of the @code{errno} code @var{ERRNUM}.  When
successful return true, otherwise return false.

@example
declare SYM

mmux-bash-pointers-errno-to-string SYM $libc_ENOMEM
"$SYM"  @result{} ENOMEM
@end example
@end defun

@c page
@c ------------------------------------------------------------
@c Appendices.
@c ------------------------------------------------------------

@include lgpl-3.0.texi
@include fdl-1.3.texi

@c page
@node shared library
@appendix Using the shared library


@value{PACKAGE} installs a shared library:

@center @file{libmmux-bash-pointers.so}

@noindent
and a C language header:

@center @file{libmmux-bash-pointers.h}

@noindent
we can write code that links to the shared library to reuse some of its facilities.  @ref{overview
linking} for details.

@menu
* shared library config::       How to configure a package to link the shared library.
* shared library version::      Version functions.
* shared library parsers::      Parsing string representations of C language types.
* shared library sprinters::    Printing string representations of C language types.
@end menu

@c page
@node shared library config
@appendixsec How to configure a package to link the shared library


It happens that some rare platform may not implement the C language types @code{long long} and
@code{long double}.  When writing a package that interfaces with the shared library, we must define
preprocessor symbols to specify if a type is implemented:

@example
#define HAVE_LONG_LONG_INT              1
#define HAVE_UNSIGNED_LONG_LONG         1
#define HAVE_LONG_DOUBLE                1
@end example

@noindent
when using the @gnu{} Autotools, we can put the following code in @file{configure.ac}:

@example
AC_TYPE_LONG_LONG_INT
AC_TYPE_UNSIGNED_LONG_LONG_INT
AC_TYPE_LONG_DOUBLE
@end example

@c page
@node shared library version
@appendixsec Version functions


The installed libraries follow version numbering as established by the @gnu{} Autotools.  For an
explanation of interface numbers as managed by @gnu{} Libtool @xref{Libtool versioning, interface,
Libtool's versioning system, libtool, Shared library support for @gnu{}}.


@deftypefun {char const *} mmux_bash_pointers_version_string (void)
Return a pointer to a statically allocated @asciiz{} string representing the interface version
number.
@end deftypefun


@deftypefun int mmux_bash_pointers_version_interface_current (void)
Return an integer representing the library interface current number.
@end deftypefun


@deftypefun int mmux_bash_pointers_version_interface_revision (void)
Return an integer representing the library interface current revision number.
@end deftypefun


@deftypefun int mmux_bash_pointers_version_interface_age (void)
Return an integer representing the library interface current age.
@end deftypefun

@c page
@node shared library parsers
@appendixsec Parsing string representations of C language types


@macro MmuxDefineCFunctionParser{STEM,TYPE}
@deftypefun int mmux_bash_pointers_parse_\STEM\ (\TYPE\ * @var{PTR}, char const * @var{STR}, char const * @var{CALLER_NAME})
Parse a string which is meant to be the representation of a C language type @code{\TYPE\}; when
successful store the result in the variable referenced by @var{PTR}, then return
@code{EXECUTION_SUCCESS}; otherwise leave @var{PTR} untouched and return @code{EXECUTION_FAILURE}.

In case of failure: if @var{CALLER_NAME} is not @cnull{}, print on @stderr{} a message describing
the parsing error; @var{CALLER_NAME} must reference an @asciiz{} string representing the entity that
requested the parsing operation, for example: the name of a builtin.
@end deftypefun

@end macro


@MmuxDefineCFunctionParser{pointer,void *}

@MmuxDefineCFunctionParser{schar,signed char}
@MmuxDefineCFunctionParser{uchar,unsigned char}
@MmuxDefineCFunctionParser{sint,signed int}
@MmuxDefineCFunctionParser{uint,unsigned int}
@MmuxDefineCFunctionParser{slong,signed long}
@MmuxDefineCFunctionParser{ulong,unsigned long}
@MmuxDefineCFunctionParser{sllong,signed long long}
@MmuxDefineCFunctionParser{ullong,unsigned long long}
@MmuxDefineCFunctionParser{float,float}
@MmuxDefineCFunctionParser{double,double}
@MmuxDefineCFunctionParser{ldouble,long double}
@MmuxDefineCFunctionParser{complex,double complex}

@MmuxDefineCFunctionParser{sint8,int8_t}
@MmuxDefineCFunctionParser{uint8,uint8_t}
@MmuxDefineCFunctionParser{sint16,int16_t}
@MmuxDefineCFunctionParser{uint16,uint16_t}
@MmuxDefineCFunctionParser{sint32,int32_t}
@MmuxDefineCFunctionParser{uint32,uint32_t}
@MmuxDefineCFunctionParser{sint64,int64_t}
@MmuxDefineCFunctionParser{uint64,uint64_t}

@MmuxDefineCFunctionParser{ssize,ssize_t}
@MmuxDefineCFunctionParser{usize,size_t}
@MmuxDefineCFunctionParser{intmax, intmax_t}
@MmuxDefineCFunctionParser{intptr, intptr_t}
@MmuxDefineCFunctionParser{mode, mode_t}
@MmuxDefineCFunctionParser{off, off_t}
@MmuxDefineCFunctionParser{pid, pid_t}
@MmuxDefineCFunctionParser{uid, uid_t}
@MmuxDefineCFunctionParser{gid, gid_t}

@c page
@node shared library sprinters
@appendixsec Printing string representations of C language types


@macro MmuxDefineCFunctionSprinter{STEM,TYPE}
@deftypefun int mmux_bash_pointers_sprint_\STEM\ (char * @var{STRPTR}, size_t @var{LEN}, \TYPE\ @var{VALUE})
Generate a string representation of @var{VALUE} and store it, in @asciiz{} format, in the string
referenced by @var{STRPTR}, which can hold at most @var{LEN} bytes (terminating zero included).
When successful return @code{EXECUTION_SUCCESS}; otherwise leave @var{STRPTR} untouched and return
@code{EXECUTION_FAILURE}.
@end deftypefun

@end macro


@MmuxDefineCFunctionSprinter{pointer,void *}

@MmuxDefineCFunctionSprinter{schar,signed char}
@MmuxDefineCFunctionSprinter{uchar,unsigned char}
@MmuxDefineCFunctionSprinter{sint,signed int}
@MmuxDefineCFunctionSprinter{uint,unsigned int}
@MmuxDefineCFunctionSprinter{slong,signed long}
@MmuxDefineCFunctionSprinter{ulong,unsigned long}
@MmuxDefineCFunctionSprinter{sllong,signed long long}
@MmuxDefineCFunctionSprinter{ullong,unsigned long long}
@MmuxDefineCFunctionSprinter{float,float}
@MmuxDefineCFunctionSprinter{double,double}
@MmuxDefineCFunctionSprinter{ldouble,long double}
@MmuxDefineCFunctionSprinter{complex,double complex}

@MmuxDefineCFunctionSprinter{sint8,int8_t}
@MmuxDefineCFunctionSprinter{uint8,uint8_t}
@MmuxDefineCFunctionSprinter{sint16,int16_t}
@MmuxDefineCFunctionSprinter{uint16,uint16_t}
@MmuxDefineCFunctionSprinter{sint32,int32_t}
@MmuxDefineCFunctionSprinter{uint32,uint32_t}
@MmuxDefineCFunctionSprinter{sint64,int64_t}
@MmuxDefineCFunctionSprinter{uint64,uint64_t}

@MmuxDefineCFunctionSprinter{ssize,ssize_t}
@MmuxDefineCFunctionSprinter{usize,size_t}
@MmuxDefineCFunctionSprinter{intmax, intmax_t}
@MmuxDefineCFunctionSprinter{intptr, intptr_t}
@MmuxDefineCFunctionSprinter{mode, mode_t}
@MmuxDefineCFunctionSprinter{off, off_t}
@MmuxDefineCFunctionSprinter{pid, pid_t}
@MmuxDefineCFunctionSprinter{uid, uid_t}
@MmuxDefineCFunctionSprinter{gid, gid_t}

@c page
@node references
@appendix Bibliography and references


The documentation of @value{PACKAGE} is available online:

@center @value{DocumentationUrl}

@noindent
development takes place at:

@center @value{GithubUrl}

@noindent
the package @mbfl{} is available online:

@center @url{http://github.com/marcomaggi/mbfl/}

@c page
@node concept index
@appendix An entry for each concept

@printindex cp

@node function index
@appendix An entry for each function.

@printindex fn

@node variable index
@appendix An entry for each variable.

@printindex vr

@node type index
@appendix An entry for each type.

@printindex tp

@contents
@bye

@c end of file

